### ISSUE TITLE
请问如何播放钢琴音色

### ISSUE THREAD

**Issue by dyj11** [ChinaWallace/Android_FluidSynth_MidiDriver#2]
使用MidiSynth播放音色，换了几个音色库，一直都是鼓声，请问是什么原因呢？

**Comment by ChinaWallace** [comment]
channel为9是鼓声 换别的就好了




------------------ 原始邮件 ------------------
发件人: "TheBrightestStarInTheNightSky"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午2:31
收件人: "ChinaWallace/Android_FluidSynth_MidiDriver"<Android_FluidSynth_MidiDriver@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ChinaWallace/Android_FluidSynth_MidiDriver] 请问如何播放钢琴音色 (#2)




使用MidiSynth播放音色，换了几个音色库，一直都是鼓声，请问是什么原因呢？

**Comment by dyj11** [comment]
我也更换了channel，但是并没有找到钢琴的声音，请问下channel跟鼓声、钢琴音等等是如何对照的呢？

**Comment by ChinaWallace** [comment]
MIDI有16 个通道(Channel) ，而第 10 个被默认地用作打击乐
改变音色用MidiSynth里的programChange，或者用Sonivox EAS的sendmidi方法发送0xc0（最后的0为第一个通道），后面的program参数就是你所用音色库里的对应音色，比如GS音色表里0x03是电钢琴音色
[GS音色表.txt](https://github.com/ChinaWallace/Android_FluidSynth_MidiDriver/files/3490867/GS.txt)

[midi文件分析.docx](https://github.com/ChinaWallace/Android_FluidSynth_MidiDriver/files/3490866/midi.docx)

**Comment by dyj11** [comment]
private MidiSynth midiSynth;
private int myChannel=0;
private void initMidiSynth(){
      String filePath = getCopyFile(this,"aaa.sf2");
       midiSynth = new MidiSynth(filePath);
       midiSynth.startSynth();
       midiSynth.sendProgramChange(myChannel,0x00);
}
我在代码中这样实现之后，感觉播放的音色并不是“Acoustic Grand Piano”，听不起效果不好，请问是什么原因呢？大佬

**Comment by ChinaWallace** [comment]
是因为延迟问题，midi事件越多越明显，当初也是解决了很久效果并不好，后来我用的这个billthefarmer/mididriver，我现在这个项目也集成了，不过是旧版本需更新


如果你一定要加载自己的音色库的话，在github上搜索fluidsynth或者fluidLite,不知道新版本的是否解决这个问题,或者其他方式






------------------ 原始邮件 ------------------
发件人: "TheBrightestStarInTheNightSky"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 晚上8:09
收件人: "ChinaWallace/Android_FluidSynth_MidiDriver"<Android_FluidSynth_MidiDriver@noreply.github.com>;
抄送: "蔡英瀚"<455202662@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ChinaWallace/Android_FluidSynth_MidiDriver] 请问如何播放钢琴音色 (#2)




private MidiSynth midiSynth;
 private int myChannel=0;
 private void initMidiSynth(){
 String filePath = getCopyFile(this,"aaa.sf2");
 midiSynth = new MidiSynth(filePath);
 midiSynth.startSynth();
 midiSynth.sendProgramChange(myChannel,0x00);
 }
 我在代码中这样实现之后，感觉播放的音色并不是“Acoustic Grand Piano”，听不起效果不好，请问是什么原因呢？大佬

**Comment by dyj11** [comment]
大佬，方便加个联系方式吗？我也不懂midi，但是公司现在有项目需要做，你代码里还有一些逻辑我不太明白，还想请教一下你，我的企鹅:1352761469

**Comment by ChinaWallace** [comment]
> 大佬，方便加个联系方式吗？我也不懂midi，但是公司现在有项目需要做，你代码里还有一些逻辑我不太明白，还想请教一下你，我的企鹅:1352761469

已加
